# Generated by Django 2.1.3 on 2019-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190201_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is he taking part now?'),
        ),
    ]
