# Generated by Django 2.0.7 on 2019-03-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quser_is_online'),
        ('quiz', '0008_auto_20190205_1546'),
    ]

    operations = [
    ]
