# Generated by Django 2.1.7 on 2019-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_time',
            field=models.IntegerField(default=30, verbose_name='Time for answer'),
        ),
        migrations.AddField(
            model_name='quser',
            name='answer_time',
            field=models.IntegerField(default=0, verbose_name="User's time"),
        ),
    ]
