# Generated by Django 2.1.7 on 2019-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190312_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_time',
            field=models.IntegerField(default=15, verbose_name='Time for answer'),
        ),
    ]
